/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Juneau
 * Created: May 8, 2016
 */
create table DUKE_ASSIGNEE(
ID      NUMERIC,
EMAIL   VARCHAR(100),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(150));

CREATE TABLE DUKE_ASSIGNEE_DUKE_ISSUES(
DUKEASSIGNEE_ID NUMERIC,
DUKEISSUES_ID NUMERIC);

CREATE TABLE DUKE_ISSUES(
ID      NUMERIC,
DESCRIPTION VARCHAR(2500),
SUBJECT     VARCHAR(150),
ASSIGNEE NUMERIC,
PRIORITY NUMERIC,
REQUESTOR NUMERIC,
STATUS NUMERIC);

CREATE TABLE DUKE_PRIORITY(
ID      NUMERIC,
PRIORITY    NUMERIC);

CREATE TABLE DUKE_STATUS(
ID      NUMERIC,
STATUS      VARCHAR(100));

CREATE TABLE DUKE_USER (
ID      NUMERIC,
EMAIL   VARCHAR(150),
FIRST_NAME VARCHAR(100),
LAST_NAME   VARCHAR(100));

CREATE TABLE DUKE_USER_DUKE_ISSUES (
DUKEUSER_ID NUMERIC,
DUKEISSUES_ID NUMERIC
);

INSERT INTO DUKE_PRIORITY VALUES(
1, 1);
INSERT INTO DUKE_PRIORITY VALUES(
2, 2);
INSERT INTO DUKE_PRIORITY VALUES(
3, 3);
INSERT INTO DUKE_PRIORITY VALUES(
4, 4);

INSERT INTO DUKE_STATUS VALUES (
1, 'OPEN');
INSERT INTO DUKE_STATUS VALUES (
2, 'ASSIGNED');
INSERT INTO DUKE_STATUS VALUES (
3, 'CANCELED');
INSERT INTO DUKE_STATUS VALUES (
4, 'COMPLETE');

